# Generated by Django 4.2.4 on 2023-08-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tanks', 'Tanks'), ('Healers', 'Healers'), ('DDs', 'DDs'), ('Merchants', 'Merchants'), ('Guildmasters', 'Guildmasters'), ('Questgivers', 'Questgivers'), ('Blacksmiths', 'Blacksmiths'), ('Leatherworkers', 'Leatherworkers'), ('Potion Makers', 'Potion Makers'), ('Spellmasters', 'Spellmasters')], max_length=50)),
                ('headline', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='noticeboard.advert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
